AWSTemplateFormatVersion: "2010-09-09"
Description: "EC2 Instance with Public IP CloudFormation"

Parameters:
  VPCId:
    Type: String
    Description: "VPC ID"

Resources:
  EC2InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: EC2 Instance Security Group
      VpcId: !Ref VPCId

  EC2Instance:F
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: lenovo
      ImageId: ami-051f7e7f6c2f40dc1
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: subnet-02ccfa57d34040c86


Outputs:
  EC2InstancePublicIP:
    Description: "Public IP Address of the EC2 Instance"
    Value: !GetAtt EC2Instance.PublicIp
